USE QLSV_AT;
GO

IF OBJECT_ID('dbo.ADMIN_AUDIT_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ADMIN_AUDIT_LOG (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USERNAME VARCHAR(50) NOT NULL,
        ACTION_CODE VARCHAR(50) NOT NULL,
        ACTION_LABEL NVARCHAR(200) NOT NULL,
        ENTITY_TYPE VARCHAR(50) NULL,
        ENTITY_ID NVARCHAR(100) NULL,
        MESSAGE NVARCHAR(500) NOT NULL,
        STATUS VARCHAR(20) NOT NULL
            CONSTRAINT DF_ADMIN_AUDIT_STATUS DEFAULT ('SUCCESS'),
        IP_ADDRESS VARCHAR(64) NULL,
        USER_AGENT NVARCHAR(300) NULL,
        CREATED_AT DATETIME2(0) NOT NULL
            CONSTRAINT DF_ADMIN_AUDIT_CREATED_AT
            DEFAULT (DATEADD(HOUR, 7, SYSUTCDATETIME()))
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.ADMIN_AUDIT_LOG')
      AND name = 'IX_ADMIN_AUDIT_LOG_CREATED_AT'
)
BEGIN
    CREATE INDEX IX_ADMIN_AUDIT_LOG_CREATED_AT
        ON dbo.ADMIN_AUDIT_LOG(CREATED_AT DESC, ID DESC);
END;
GO
