/*
  Khóa CRT/Diffie-Hellman ổn định theo người dùng.

  PIN không còn được dùng trực tiếp làm khóa riêng sau khi tài khoản được
  chuyển đổi. PIN chỉ mở một "phong bì khóa" AES-256-GCM nhỏ. Vì vậy đổi PIN
  chỉ cập nhật một dòng tại bảng này và PIN_HASH, không quét DIEM_CRT.
*/
IF OBJECT_ID('dbo.USER_CRYPTO_KEY', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.USER_CRYPTO_KEY (
    PRINCIPAL_TYPE VARCHAR(20) NOT NULL,
    PRINCIPAL_ID VARCHAR(50) NOT NULL,
    KEY_CIPHERTEXT NVARCHAR(MAX) NOT NULL,
    KEY_SALT VARCHAR(128) NOT NULL,
    KEY_IV VARCHAR(64) NOT NULL,
    KEY_AUTH_TAG VARCHAR(64) NOT NULL,
    KDF_VERSION VARCHAR(30) NOT NULL,
    ALGORITHM_VERSION VARCHAR(30) NOT NULL,
    KEY_ORIGIN VARCHAR(30) NOT NULL
      CONSTRAINT DF_USER_CRYPTO_KEY_ORIGIN DEFAULT ('LEGACY_PIN'),
    KEY_VERSION INT NOT NULL
      CONSTRAINT DF_USER_CRYPTO_KEY_VERSION DEFAULT (1),
    CREATED_AT DATETIME2(0) NOT NULL
      CONSTRAINT DF_USER_CRYPTO_KEY_CREATED_AT
      DEFAULT (DATEADD(HOUR, 7, SYSUTCDATETIME())),
    UPDATED_AT DATETIME2(0) NOT NULL
      CONSTRAINT DF_USER_CRYPTO_KEY_UPDATED_AT
      DEFAULT (DATEADD(HOUR, 7, SYSUTCDATETIME())),
    CONSTRAINT PK_USER_CRYPTO_KEY
      PRIMARY KEY (PRINCIPAL_TYPE, PRINCIPAL_ID),
    CONSTRAINT CK_USER_CRYPTO_KEY_PRINCIPAL_TYPE
      CHECK (PRINCIPAL_TYPE IN ('GIANGVIEN', 'SINHVIEN'))
  );
END;

IF COL_LENGTH('dbo.USER_CRYPTO_KEY', 'KEY_ORIGIN') IS NULL
BEGIN
  ALTER TABLE dbo.USER_CRYPTO_KEY
    ADD KEY_ORIGIN VARCHAR(30) NOT NULL
      CONSTRAINT DF_USER_CRYPTO_KEY_ORIGIN DEFAULT ('LEGACY_PIN');
END;
